version: "3"
services:
    "db":
        build:
            context: ./test/db
        environment:
            POSTGRES_PASSWORD: lozinka123
        ports:
            - "5432:5432"
        expose:
            - "5432"
    "kefa":
        build: 
            context: .
            dockerfile: ./Dockerfile
        environment: 
            PORT: ":5000"
        ports: 
            - "5000:5000"
        depends_on:
            - "db"
    "test":
        build:
            context: ./test
        depends_on:
            - "kefa"